import type { Metadata } from "next";
import "./globals.scss";
import { ApolloProviderWrapper } from "./(lib)/apollo-provider";
import { pretendard } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "MMTalk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body>
        <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
      </body>
    </html>
  );
}
